services:
  oai-gnb:
        image: ${REGISTRY-oaisoftwarealliance/}${GNB_IMG:-oai-gnb}:${TAG:-2026.w05}
        container_name: oai-gnb
        cap_add:
            - SYS_NICE
            - IPC_LOCK
        cap_drop:
            - ALL
        privileged: true
        environment:
            USE_ADDITIONAL_OPTIONS: #Put here additional parameters for nr-softmodem executable
            UHD_IMAGES_DIR : "/usr/share/uhd/images"
            ASAN_OPTIONS: detect_leaks=0
        network_mode: host
        volumes:
            - ./confs/gnb_template.conf:/opt/oai-gnb/etc/gnb.conf
            - /dev/bus/usb/:/dev/bus/usb/
            - /usr/local/share/uhd/images:/usr/share/uhd/images
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5
            
  oai-nr-ue:
        image: ${REGISTRY-oaisoftwarealliance/}${NRUE_IMG:-oai-nr-ue}:${TAG:-2026.w05}
        container_name: oai-nr-ue
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  
            - NET_RAW    
            - SYS_NICE
        privileged: true
        environment:
            UHD_IMAGES_DIR : "/usr/share/uhd/images"
            #USE_ADDITIONAL_OPTIONS: #Put here additional parameters for nr-uesoftmodem executable  
        network_mode: host
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ./confs/ue_template.conf:/opt/oai-nr-ue/etc/nr-ue.conf
            - /dev/bus/usb/:/dev/bus/usb/
            - /usr/local/share/uhd/images:/usr/share/uhd/images
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            start_period: 10s
            start_interval: 500ms
            interval: 10s
            timeout: 5s
            retries: 5        

networks:
  default:
    external: true
    name: docker_open5gs_default
