FROM ubuntu:noble AS oai-ue
ARG TARGETARCH
ARG BUILD_OPTION
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes \
       build-essential \
       ccache \
       psmisc \
       git \
       xxd \
       libpcre2-dev \
       python3-dev \
       bison \
       flex \
       m4 \
       python3-pip \
       swig \
       gdb \
       wget && \
    pip3 install --ignore-installed pyyaml --break-system-packages

RUN apt-get update && \
    apt-get upgrade --yes && \
    apt-get install --yes \
        software-properties-common \
        procps \
        libsctp1 \
        libboost-chrono1.83.0 \
        libboost-date-time1.83.0 \
        libboost-filesystem1.83.0 \
        libboost-regex1.83.0 \
        libboost-serialization1.83.0 \
        libboost-thread1.83.0 \
        libboost-system1.83.0 \
        libboost-program-options1.83.0 \
        tzdata \
        liblapacke \
        libblas3 \
        libconfig9 \
        openssl \
        net-tools \
        gdb \
        python3 \
        python3-six \
        python3-requests \
        libusb-1.0-0 \
        iputils-ping \
        iproute2 \
        iperf3 \
        iperf \
        libyaml-cpp-dev && \
        /bin/bash -c 'if [[ "$BUILD_OPTION" = "--sanitize" ]]; then DEBIAN_FRONTEND=noninteractive apt-get install --yes \
        libasan8 \
        libubsan1; fi' && \
        apt-get clean -y && \
        rm -rf /var/lib/apt/lists/*
    

WORKDIR /opt/oai/bin
COPY ./oai-custom/cmake_targets/ran_build/build/ \
     ./

COPY ./oai-custom/docker/scripts/nr_ue_entrypoint.sh ./entrypoint.sh
COPY ./oai-custom/docker/scripts/check-prach-io.sh ./check-prach-io.sh

COPY ./oai-custom/cmake_targets/ran_build/build/libcoding.so \
    ./oai-custom/cmake_targets/ran_build/build/libparams_libconfig.so \
    ./oai-custom/cmake_targets/ran_build/build/libdfts.so \
    ./oai-custom/cmake_targets/ran_build/build/libldpc*.so \
    ./oai-custom/cmake_targets/ran_build/build/libparams_yaml.so \
    ./oai-custom/cmake_targets/ran_build/build/liboai_usrpdevif.so \
    /usr/local/lib/

COPY ./uhd/uhd_find_devices /usr/local/bin/
COPY ./uhd/libuhd.so.4.8.0 /usr/local/lib/

RUN /bin/bash -c "ln -s /usr/local/lib/liboai_usrpdevif.so /usr/local/lib/liboai_device.so" && \
    ldconfig 

WORKDIR /opt/oai

ENV TINI_VERSION=v0.19.0
RUN wget https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${TARGETARCH} -O /tini && chmod +x /tini

ENV YQ_VERSION=v4.2.0
RUN wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH} -O /usr/local/bin/yq &&\
    chmod +x /usr/local/bin/yq

CMD ["/opt/oai/bin/nr-uesoftmodem"]
ENTRYPOINT ["/tini", "-v", "--", "/opt/oai/bin/entrypoint.sh"]
